// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Task_.Server.Data;

#nullable disable

namespace My_Task_.Server.Migrations
{
    [DbContext(typeof(My_Task_ServerContext))]
    [Migration("20230731065510_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("My_Task_.Shared.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskItemId"));

                    b.Property<bool>("IsCompeted")
                        .HasColumnType("bit");

                    b.Property<bool>("NoSubTask")
                        .HasColumnType("bit");

                    b.Property<string>("TaskItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TaskItemRepeat")
                        .HasColumnType("bit");

                    b.Property<string>("TaskItemStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskItemStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskItemStatus")
                        .HasColumnType("int");

                    b.HasKey("TaskItemId");

                    b.ToTable("TaskItem");
                });
#pragma warning restore 612, 618
        }
    }
}
